# Generated by Django 4.2.2 on 2023-06-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_picture_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='default.png', upload_to='profile_pictures'),
        ),
    ]
