# Generated by Django 4.2.2 on 2023-06-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='default.avif', upload_to='profile_pictures'),
        ),
    ]
