# Generated by Django 4.2.2 on 2023-06-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='Enter value', max_length=150),
            preserve_default=False,
        ),
    ]
